<?php
/**
 * Rebuild the plugin asset bundles.
 *
 *     php build-assets.php
 *
 * The application loads one stylesheet and one script per plugin instead of
 * six and four. Against a single-threaded PHP server every request is served
 * in turn, so the request count is what page load actually costs.
 *
 * The individual source files remain the ones to edit. Run this afterwards --
 * nothing rebuilds automatically, so an edit that is not followed by a build
 * will not reach the browser.
 */

$root = __DIR__;

$bundles = array(
    'plugins/Superbee/Assets/css/bundle.css' => array(
        // tokens first: the other two read its custom properties
        'plugins/Superbee/Assets/css/tokens.css',
        'plugins/Superbee/Assets/css/shell.css',
        'plugins/Superbee/Assets/css/kanboard-sync.css',
    ),
    'plugins/TaskManager/Assets/css/bundle.css' => array(
        'plugins/TaskManager/Assets/css/taskmanager.css',
        'plugins/TaskManager/Assets/css/dashboard.css',
        'plugins/TaskManager/Assets/css/grid.css',
    ),
    'plugins/TaskManager/Assets/js/bundle.js' => array(
        'plugins/TaskManager/Assets/js/taskmanager.js',
        'plugins/TaskManager/Assets/js/grid.js',
        'plugins/TaskManager/Assets/js/task-panel.js',
        'plugins/TaskManager/Assets/js/status-select.js',
    ),
);

$failed = false;

foreach ($bundles as $target => $sources) {
    $isJs  = substr($target, -3) === '.js';
    $names = array_map('basename', $sources);
    $out   = "/* Generated by build-assets.php - do not edit.\n".
             "   Sources, in order: ".implode(', ', $names)." */\n";

    foreach ($sources as $source) {
        $path = $root.'/'.$source;

        if (! is_readable($path)) {
            fwrite(STDERR, "missing source: $source\n");
            $failed = true;
            continue 2;
        }

        $out .= "\n/* ---- ".basename($source)." ---- */\n";
        $out .= file_get_contents($path);

        // A source file without a trailing semicolon would otherwise run into
        // whatever follows it.
        if ($isJs) {
            $out .= "\n;\n";
        }
    }

    file_put_contents($root.'/'.$target, $out);
    printf("%-52s %7d bytes  <- %d files\n", $target, strlen($out), count($sources));
}

if ($failed) {
    fwrite(STDERR, "\nbuild incomplete\n");
    exit(1);
}

echo "\ndone\n";
